# Generated by Django 3.2.12 on 2022-03-12 09:59

import diet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('recipe_image', models.ImageField(upload_to=diet.models.upload_path_handler)),
                ('recipe_description', models.TextField()),
                ('recipe_ingredients', models.TextField()),
                ('recipe_steps', models.TextField()),
                ('cooking_time', models.CharField(max_length=255)),
                ('recipe_added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['recipe_added_at'],
            },
        ),
    ]
