# Generated by Django 4.0.1 on 2022-03-12 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('instructions', models.TextField(blank=True, max_length=1000)),
                ('tips', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='gym/exercises/')),
                ('url', models.URLField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('primary_muscles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_muscles', to='body.muscle')),
                ('secondary_muscles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_muscles', to='body.muscle')),
                ('user_prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.workoutsession')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(default=0)),
                ('reps_unit', models.CharField(choices=[('RE', 'Reps'), ('MI', 'Minutes'), ('SE', 'Seconds'), ('KM', 'kilometers'), ('UF', 'Until Failure')], default='RE', max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_unit', models.CharField(choices=[('KG', 'Kg.'), ('BW', 'Body Weight'), ('KH', 'Kms per hour')], default='RE', max_length=2)),
                ('user_prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sets', models.IntegerField(default=3)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise')),
                ('sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='gym.set')),
                ('user_prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram')),
            ],
        ),
    ]
