# Generated by Django 4.0.1 on 2022-03-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_programphase_user_prog_id_and_more'),
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='user_prog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='user_prog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram'),
        ),
        migrations.AlterField(
            model_name='set',
            name='user_prog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram'),
        ),
    ]
