# Generated by Django 3.2.12 on 2022-03-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
        ('planner', '0003_auto_20220312_2020'),
        ('gym', '0002_exercise_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workout_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.workoutsession'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscles',
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_muscles', to='body.muscle'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscles',
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_muscles', to='body.muscle'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='sets',
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='sets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='gym.set'),
            preserve_default=False,
        ),
    ]
