# Generated by Django 4.0.1 on 2022-03-12 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='planner/program/')),
                ('summary', models.TextField(blank=True, max_length=1500)),
                ('level', models.CharField(choices=[('BE', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='IN', max_length=2)),
                ('goal', models.CharField(choices=[('BU', 'Bulking'), ('CU', 'Cutting'), ('MA', 'Maintaining')], default='MA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('exercise_in_program', models.IntegerField(default=0)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.program')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('recommendations', models.TextField(blank=True, max_length=1000)),
                ('motivation_quotes', models.TextField(blank=True, max_length=1000)),
                ('user_prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.workoutsession')),
                ('user_prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='planner/workout/')),
                ('user_prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.workoutday')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('weeks_duration', models.PositiveIntegerField()),
                ('user_prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram')),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
