# Generated by Django 4.0.1 on 2022-03-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programphase',
            name='user_prog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user_prog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='user_prog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='user_prog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.userprogram'),
        ),
    ]
