# Generated by Django 3.2.12 on 2022-03-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20220312_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='phases',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='day',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='exercises',
        ),
        migrations.AddField(
            model_name='programphase',
            name='program_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutday',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.workout'),
            preserve_default=False,
        ),
    ]
