# Generated by Django 3.2.12 on 2022-03-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20220312_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutday',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.workoutday'),
            preserve_default=False,
        ),
    ]
